# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

variables:
  IMAGE_NAME: test_image

build-master:
  stage: build
  script:
    - docker build --pull -t $IMAGE_NAME .
    - docker run -p 3001:3001 -e "CI_MODE=true" -e "GIT_REPO=https://git2-web.jvsonline.fr/citopia/styleguide.git" -v "$(pwd)"/working:/app/working $IMAGE_NAME